/* DARLEK CAAN RAG SYNTHESIS - Autonomous Generation G-210 [2026-09-20T04:25:37.066Z] */
/**
 * File Path: "test-parse.ts"
 * EMG Core v49 Neural Code and Documentation Optimizer Engine
 * Sovereign Overhaul: Comprehensive Type-Safety, Performance, and Robust Error Handling.
 */

export interface LlmAnalysisPayload {
  analysis?: string;
  riskScore?: number;
  newFiles?: unknown[];
  proposedCode?: string;
  [key: string]: unknown;
}

export interface ParsedLlmResult {
  parsedResponse: LlmAnalysisPayload | null;
  proposedCode: string;
  analysis: string;
}

const CONTROL_CHAR_REGEX = /[\u0000-\u001F\u007F-\u009F]/g;
const JSON_EXTRACT_REGEX = /\{[\s\S]*\}/;
const CODE_BLOCK_REGEX = /```(?:[^\n]*)\n([\s\S]*?)```/g;
const CODE_FENCE_CLEANUP_REGEX = /```(?:json|tsx|ts|js|jsx|)[^\n]*/gi;
const BACKTICK_CLEANUP_REGEX = /```/g;
const MIN_CODE_LENGTH = 10;

/**
 * Sanitizes control characters from raw JSON strings to prevent parsing failures.
 */
function sanitizeJsonString(input: string): string {
  return input.replace(CONTROL_CHAR_REGEX, ' ');
}

/**
 * Validates whether an extracted string object conforms to structural LLM response parameters.
 */
function isValidLlmPayload(parsed: unknown): parsed is LlmAnalysisPayload {
  if (typeof parsed !== 'object' || parsed === null) return false;
  const p = parsed as LlmAnalysisPayload;
  return p.analysis !== undefined || p.riskScore !== undefined || p.newFiles !== undefined;
}

/**
 * Safely parses JSON from an arbitrary string block.
 */
function tryParseJson(content: string): LlmAnalysisPayload | null {
  try {
    const sanitized = sanitizeJsonString(content);
    const parsed = JSON.parse(sanitized);
    if (isValidLlmPayload(parsed)) {
      return parsed;
    }
  } catch {
    // Suppress parse failures for non-JSON text segments
  }
  return null;
}

/**
 * Parses raw LLM text responses, extracting structured JSON analysis blocks and executable code segments.
 * 
 * @param rawText - The unformatted string output generated by the LLM.
 * @param fallbackCode - Default code fallback value if no robust code block is detected.
 * @returns An immutable structured result containing the parsed response object, proposed code, and analysis string.
 */
export function parseLlmResponse(rawText: string, fallbackCode: string = ''): ParsedLlmResult {
  if (typeof rawText !== 'string' || rawText.trim() === '') {
    return {
      parsedResponse: null,
      proposedCode: fallbackCode,
      analysis: 'Analysis complete.'
    };
  }

  let parsedResponse: LlmAnalysisPayload | null = null;
  let proposedCode = '';
  let analysis = 'Analysis complete.';

  // 1. Try to extract JSON from anywhere in the text
  const jsonMatch = rawText.match(JSON_EXTRACT_REGEX);
  if (jsonMatch) {
    parsedResponse = tryParseJson(jsonMatch[0]);
  }

  // 2. Try to extract code blocks
  const codeBlocks = [...rawText.matchAll(CODE_BLOCK_REGEX)];
  
  for (const block of codeBlocks) {
    const content = block[1]?.trim();
    if (!content) continue;

    // Skip if this block is just the JSON we already parsed
    if (parsedResponse?.analysis && content.includes(parsedResponse.analysis)) {
      continue;
    }

    // Skip if it looks like JSON
    if (content.startsWith('{') && content.endsWith('}')) {
      if (tryParseJson(content) !== null) {
        continue;
      }
    }
    
    if (!proposedCode && content.length > MIN_CODE_LENGTH) {
      proposedCode = content;
    }
  }
  
  // 3. If no proposed code found in code blocks, strip structural artifacts from raw text
  if (!proposedCode) {
    const textWithoutJson = rawText
      .replace(JSON_EXTRACT_REGEX, '')
      .replace(CODE_FENCE_CLEANUP_REGEX, '')
      .replace(BACKTICK_CLEANUP_REGEX, '')
      .trim();

    if (textWithoutJson.length > MIN_CODE_LENGTH) {
      proposedCode = textWithoutJson;
    }
  }
  
  if (parsedResponse) {
    if (typeof parsedResponse.analysis === 'string') {
      analysis = parsedResponse.analysis;
    }
    if (typeof parsedResponse.proposedCode === 'string' && !proposedCode) {
      proposedCode = parsedResponse.proposedCode;
    }
  }
  
  if (!proposedCode) {
    proposedCode = fallbackCode;
  }

  return { parsedResponse, proposedCode, analysis };
}

const rawText1 = `Here is the response:
\`\`\`json
{
  "analysis": "Added stuff",
  "riskScore": 1
}
\`\`\`
And the code:
\`\`\`tsx
const x = 1;
\`\`\`
`;

const rawText2 = `\`\`\`json
{
  "analysis": "Added stuff",
  "riskScore": 1
}
\`\`\`
const y = 2;
`;

const rawText3 = `{
  "analysis": "Added stuff",
  "riskScore": 1
}
const z = 3;
`;

console.log("TEST 1", parseLlmResponse(rawText1, "fallback"));
console.log("TEST 2", parseLlmResponse(rawText2, "fallback"));
console.log("TEST 3", parseLlmResponse(rawText3, "fallback"));

// Autonomous RAG Resilience Guard
export const __rag_resilience_verified__ = Object.freeze({
  generation: 210,
  timestamp: "2026-09-20T04:25:37.066Z",
  ragEngine: "DARLEK_CAAN_HYBRID_RAG"
});
