import * as route0 from './app/api/brain/route.ts';
import * as route1 from './app/api/chat/route.ts';
import * as route2 from './app/api/evolution/analyze-impact/route.ts';
import * as route3 from './app/api/evolution/auto-test/route.ts';
import * as route4 from './app/api/evolution/coherence-gate/route.ts';
import * as route5 from './app/api/evolution/debate/route.ts';
import * as route6 from './app/api/evolution/health/route.ts';
import * as route7 from './app/api/evolution/orchestra/route.ts';
import * as route8 from './app/api/evolution/propose/route.ts';
import * as route9 from './app/api/extract-text/route.ts';
import * as route10 from './app/api/github/branches/route.ts';
import * as route11 from './app/api/github/bulk-commit/route.ts';
import * as route12 from './app/api/github/create-branch/route.ts';
import * as route13 from './app/api/github/create-repo/route.ts';
import * as route14 from './app/api/github/create-system-repo/route.ts';
import * as route15 from './app/api/github/delete-file/route.ts';
import * as route16 from './app/api/github/push-enhancements/route.ts';
import * as route17 from './app/api/github/read-file/route.ts';
import * as route18 from './app/api/github/repo-status/route.ts';
import * as route19 from './app/api/github/scan/route.ts';
import * as route20 from './app/api/github/user-repos/route.ts';
import * as route21 from './app/api/github/write-file/route.ts';
import * as route22 from './app/api/learning-logs/sync/route.ts';
import * as route23 from './app/api/logs/sync/route.ts';
import * as route24 from './app/api/route.ts';
import * as route25 from './app/api/setup/test-connection/route.ts';
import * as route26 from './app/api/system/reboot/route.ts';
import * as route27 from './app/api/system/scaffold/route.ts';
import * as route28 from './app/api/validate/route.ts';
import * as route29 from './app/api/evolution/lock/route.ts';

const apiRoutes = {};
apiRoutes['/api/brain'] = route0;
apiRoutes['/api/chat'] = route1;
apiRoutes['/api/evolution/analyze-impact'] = route2;
apiRoutes['/api/evolution/auto-test'] = route3;
apiRoutes['/api/evolution/coherence-gate'] = route4;
apiRoutes['/api/evolution/debate'] = route5;
apiRoutes['/api/evolution/health'] = route6;
apiRoutes['/api/evolution/orchestra'] = route7;
apiRoutes['/api/evolution/propose'] = route8;
apiRoutes['/api/evolution/lock'] = route29;
apiRoutes['/api/extract-text'] = route9;
apiRoutes['/api/github/branches'] = route10;
apiRoutes['/api/github/bulk-commit'] = route11;
apiRoutes['/api/github/create-branch'] = route12;
apiRoutes['/api/github/create-repo'] = route13;
apiRoutes['/api/github/create-system-repo'] = route14;
apiRoutes['/api/github/delete-file'] = route15;
apiRoutes['/api/github/push-enhancements'] = route16;
apiRoutes['/api/github/read-file'] = route17;
apiRoutes['/api/github/repo-status'] = route18;
apiRoutes['/api/github/scan'] = route19;
apiRoutes['/api/github/user-repos'] = route20;
apiRoutes['/api/github/write-file'] = route21;
apiRoutes['/api/learning-logs/sync'] = route22;
apiRoutes['/api/logs/sync'] = route23;
apiRoutes['/api'] = route24;
apiRoutes['/api/setup/test-connection'] = route25;
apiRoutes['/api/system/reboot'] = route26;
apiRoutes['/api/system/scaffold'] = route27;
apiRoutes['/api/validate'] = route28;

export { apiRoutes };
